import asyncio
import json
import os
from datetime import datetime, timedelta
import mcp.types as types
from mcp.server import Server
from mcp.server.stdio import stdio_server

from database import Database, LOGS_COLLECTION, USERS_COLLECTION
from autonomous_agent import ALERTS_COLLECTION
from reports import generate_daily_report_pdf
from ai_agent import SecurityAIAgent

# Initialize the MCP Server
server = Server("sentinel-mcp-server")

@server.list_tools()
async def handle_list_tools() -> list[types.Tool]:
    """List available tools for the Sentinel MCP Server."""
    return [
        types.Tool(
            name="read_security_logs",
            description="Read authentication and security logs from the Sentinel database. Use this to investigate user activity or spoofing attempts.",
            inputSchema={
                "type": "object",
                "properties": {
                    "limit": {"type": "integer", "description": "Number of logs to retrieve (max 100)"},
                    "risk_level": {"type": "string", "description": "Filter by risk level (HIGH, MEDIUM, LOW)"},
                    "status": {"type": "string", "description": "Filter by status (success, spoof, failed)"}
                }
            }
        ),
        types.Tool(
            name="read_agent_alerts",
            description="Read real-time threat alerts generated by the Sentinel Autonomous AI Agent.",
            inputSchema={
                "type": "object",
                "properties": {
                    "limit": {"type": "integer", "description": "Number of alerts to retrieve"}
                }
            }
        ),
        types.Tool(
            name="generate_security_report",
            description="Generates the official Sentinel SOC PDF report and saves it to the local filesystem.",
            inputSchema={
                "type": "object",
                "properties": {
                    "output_path": {"type": "string", "description": "Absolute filesystem path to save the PDF. E.g., /tmp/sentinel_report.pdf"}
                },
                "required": ["output_path"]
            }
        )
    ]

@server.call_tool()
async def handle_call_tool(name: str, arguments: dict | None) -> list[types.TextContent]:
    """Handle tool executions requested by the AI Assistant."""
    if not arguments:
        arguments = {}

    db = Database.get_db()

    if name == "read_security_logs":
        logs_col = db[LOGS_COLLECTION]
        limit = min(arguments.get("limit", 20), 100)
        query = {}
        
        if "risk_level" in arguments:
            query["riskLevel"] = arguments["risk_level"].upper()
        if "status" in arguments:
            query["status"] = arguments["status"]
            
        logs = await logs_col.find(query).sort("timestamp", -1).to_list(length=limit)
        
        # Convert objects to string for JSON serialization
        for log in logs:
            log["_id"] = str(log["_id"])
            if isinstance(log.get("timestamp"), datetime):
                log["timestamp"] = log["timestamp"].isoformat()
                
        return [types.TextContent(type="text", text=json.dumps(logs, indent=2))]

    elif name == "read_agent_alerts":
        alerts_col = db[ALERTS_COLLECTION]
        limit = min(arguments.get("limit", 10), 50)
        
        alerts = await alerts_col.find().sort("timestamp", -1).to_list(length=limit)
        
        for alert in alerts:
            alert["_id"] = str(alert["_id"])
            if isinstance(alert.get("timestamp"), datetime):
                alert["timestamp"] = alert["timestamp"].isoformat()
                
        return [types.TextContent(type="text", text=json.dumps(alerts, indent=2))]

    elif name == "generate_security_report":
        output_path = arguments.get("output_path")
        if not output_path:
            return [types.TextContent(type="text", text="Error: output_path is required")]
            
        logs_col = db[LOGS_COLLECTION]
        one_day_ago = datetime.now() - timedelta(hours=24)
        all_logs = await logs_col.find({"timestamp": {"$gte": one_day_ago}}).to_list(length=1000)
        
        success = sum(1 for l in all_logs if l.get("status") == "success")
        highRisk = sum(1 for l in all_logs if l.get("status") == "spoof")
        suspicious = len(all_logs) - success - highRisk
        
        metrics = {
            "total": len(all_logs), "success": success, 
            "suspicious": suspicious, "highRisk": highRisk
        }
        
        threat_logs = [l for l in all_logs if l.get("riskLevel") in ["HIGH", "MEDIUM"]]
        threat_logs = sorted(threat_logs, key=lambda x: x.get("timestamp", datetime.min), reverse=True)[:20]
        
        ai_summary = "Generated via MCP Server."
        try:
            agent = SecurityAIAgent()
            recent_100 = sorted(all_logs, key=lambda x: x.get("timestamp", datetime.min), reverse=True)[:100]
            ai_summary = await agent.generate_daily_summary(recent_100)
        except Exception:
            pass
            
        pdf_bytes = generate_daily_report_pdf(metrics, threat_logs, ai_summary)
        
        try:
            # Write PDF to filesystem
            with open(output_path, "wb") as f:
                f.write(pdf_bytes)
            return [types.TextContent(type="text", text=f"Successfully generated and saved SOC report to {output_path}")]
        except Exception as e:
            return [types.TextContent(type="text", text=f"Failed to save report: {e}")]

    else:
        raise ValueError(f"Unknown tool: {name}")

async def main():
    # Connect to MongoDB before starting MCP
    await Database.connect()
    
    # Run the MCP stdio server
    options = server.create_initialization_options()
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, options)

if __name__ == "__main__":
    asyncio.run(main())
