import { useAlerts, useResolveAlert } from "@/hooks/use-alerts";
import { Button } from "@/components/ui/button";
import { ShieldAlert } from "lucide-react";
import { TechCard } from "@/components/TechCard";

export function AgentAlertsView() {
  const { data: alerts } = useAlerts();
  const resolveAlert = useResolveAlert();

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-display font-bold text-white mb-2">Autonomous Agent Alerts</h2>
          <p className="text-muted-foreground text-sm">
            Real-time threat detections generated by the AI background worker.
          </p>
        </div>
      </div>

      {alerts && alerts.length > 0 ? (
        <div className="space-y-4">
          {alerts.map((alert) => (
            <div key={alert.id} className={`p-4 rounded-lg border ${alert.resolved ? 'bg-white/5 border-white/10 opacity-70' : 'bg-red-500/10 border-red-500/30'}`}>
              <div className="flex justify-between items-start mb-2">
                <div className="flex items-center gap-2">
                  <ShieldAlert className={`w-5 h-5 ${alert.resolved ? 'text-muted-foreground' : 'text-red-400'}`} />
                  <span className="font-bold text-white/90">Threat Detected: {alert.severity} Risk</span>
                  <span className="text-xs text-muted-foreground ml-2">
                    {new Date(alert.timestamp).toLocaleString()}
                  </span>
                </div>
                {!alert.resolved && (
                  <Button 
                    size="sm" 
                    variant="outline" 
                    className="border-red-500/30 hover:bg-red-500/20 text-red-300"
                    onClick={() => resolveAlert.mutate(alert.id)}
                    disabled={resolveAlert.isPending}
                  >
                    Acknowledge & Resolve
                  </Button>
                )}
                {alert.resolved && (
                  <span className="text-xs text-emerald-400 border border-emerald-500/30 bg-emerald-500/10 px-2 py-1 rounded-full">
                    Resolved
                  </span>
                )}
              </div>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-4 text-xs font-mono text-muted-foreground p-3 bg-black/20 rounded">
                <div><span className="text-white/40">Status:</span> {alert.status}</div>
                <div><span className="text-white/40">User:</span> {alert.user}</div>
                <div><span className="text-white/40">IP:</span> {alert.ip}</div>
                <div><span className="text-white/40">Device:</span> {alert.device}</div>
              </div>
              <div className="text-sm text-white/80 border-l-2 border-indigo-500/50 pl-4 py-1">
                <div className="font-semibold text-indigo-300 mb-1">AI Analysis:</div>
                <div className="prose prose-invert max-w-none text-xs">
                  {alert.analysis.split('\\n').map((line: string, i: number) => (
                    <p key={i} className="mb-1">{line}</p>
                  ))}
                </div>
              </div>
              <div className="mt-3 text-xs font-mono text-red-300/80 bg-red-500/5 p-2 rounded inline-block">
                Action Taken: {alert.action_taken}
              </div>
            </div>
          ))}
        </div>
      ) : (
        <TechCard className="bg-white/5 border-white/10 p-8 text-center">
          <ShieldAlert className="w-12 h-12 text-muted-foreground/50 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-white/90 mb-1">No Active Threats</h3>
          <p className="text-muted-foreground text-sm">The Autonomous Agent is monitoring your systems.</p>
        </TechCard>
      )}
    </div>
  );
}
